### ISSUE TITLE
Build with not CoreCLR 3.1 sources are broken.

### ISSUE THREAD

**Issue by viewizard** [Samsung/netcoredbg#47]
Note, that https://github.com/Samsung/netcoredbg/commit/57221dd4daccdc52a1a1202cf644dfb15f6f9b4f broke netcoredbg build in case of not CoreCLR 3.1 sources usage. Only build with CoreCLR 3.1 sources are supported now.
Broken build looks like:
https://travis-ci.org/github/Samsung/netcoredbg/jobs/738317489
```
...
c:\users\travis\build\samsung\netcoredbg\src\debug\netcoredbg\cputil.cpp(116): error C2065: 'CTL_E_OVERFLOW': undeclared identifier [C:\Users\travis\build\Samsung\netcoredbg\build\src\debug\netcoredbg\netcoredbg.vcxproj]
...
```

We are working on fix at this moment.

**Comment by viewizard** [comment]
Fixed.
