### ISSUE TITLE
Not compatible with .NET 5.0

### ISSUE THREAD

**Issue by leo60228** [Samsung/netcoredbg#50]
These small patches were required to get it to compile with .NET 5.0:
```diff
diff --git a/src/debug/netcoredbg/CMakeLists.txt b/src/debug/netcoredbg/CMakeLists.txt
index 5b21494..4036361 100644
--- a/src/debug/netcoredbg/CMakeLists.txt
+++ b/src/debug/netcoredbg/CMakeLists.txt
@@ -27,6 +27,7 @@ include_directories(${CORECLR_DIR}/src/debug/inc)
 include_directories(${CORECLR_DIR}/src/debug/shim)
 include_directories(${CORECLR_DIR}/src/dlls/dbgshim)
 include_directories(${CORECLR_DIR}/src/coreclr/hosts/inc)
+include_directories(${CORECLR_DIR}/src/hosts/inc)
 
 # Build native part of the debugger
 
diff --git a/src/debug/netcoredbg/cputil.cpp b/src/debug/netcoredbg/cputil.cpp
index a51d448..eb5ca49 100644
--- a/src/debug/netcoredbg/cputil.cpp
+++ b/src/debug/netcoredbg/cputil.cpp
@@ -494,7 +494,6 @@ const char *errormessage(HRESULT hresult)
         CASE_OF(CORDBG_E_UNSUPPORTED_DELEGATE, "The delegate contains a delegate currently not supported by the API.");
         CASE_OF(PEFMT_E_64BIT, "File is PE32+.");
         CASE_OF(PEFMT_E_32BIT, "File is PE32");
-        CASE_OF(NGEN_E_SYS_ASM_NI_MISSING, "NGen cannot proceed because Mscorlib.dll does not have a native image");
         CASE_OF(CLDB_E_INTERNALERROR, "CLDB_E_INTERNALERROR");
         CASE_OF(CLR_E_BIND_ASSEMBLY_VERSION_TOO_LOW, "The bound assembly has a version that is lower than that of the request.");
         CASE_OF(CLR_E_BIND_ASSEMBLY_PUBLIC_KEY_MISMATCH, "The assembly version has a public key token that does not match that of the request.");
```
However, even with this, there are several linker errors:
```
ld: CMakeFiles/netcoredbg.dir/manageddebugger.cpp.o: in function `ManagedCallback::QueryInterface(_GUID const&, void**)':
manageddebugger.cpp:(.text._ZN15ManagedCallback14QueryInterfaceERK5_GUIDPPv[_ZN15ManagedCallback14QueryInterfaceERK5_GUIDPPv]+0x10d): undefined reference to `IID_IUnknown'
ld: CMakeFiles/netcoredbg.dir/valuewalk.cpp.o: in function `Evaluator::GetLiteralValue(ICorDebugThread*, ICorDebugType*, ICorDebugModule*, unsigned char const*, unsigned int, void const*, unsigned int, ICorDebugValue**)':
valuewalk.cpp:(.text+0xb243): undefined reference to `g_tkCorEncodeToken'
ld: valuewalk.cpp:(.text+0xb50c): undefined reference to `g_tkCorEncodeToken'
ld: CMakeFiles/netcoredbg.dir/typeprinter.cpp.o: in function `TypePrinter::NameForTypeSig(unsigned char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, IMetaDataImport*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
typeprinter.cpp:(.text+0x96f5): undefined reference to `g_tkCorEncodeToken'
ld: typeprinter.cpp:(.text+0xa159): undefined reference to `g_tkCorEncodeToken'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by leo60228** [comment]
The `g_tkCorEncodeToken` errors seem to be related to https://github.com/dotnet/runtime/commit/353919f9711e9d6b9bc772d1f9d20cee155fdf14. I'm not sure how to fix the `IID_IUnknown` error, though.

**Comment by pavel-orekhov** [comment]
`IID_IUnknown` seems relates to `corguids` lib, which depends on `coreclr/src/pal` sources (see `CORECLR_DIR` description in cmake-file).   So it is seems `+include_directories(${CORECLR_DIR}/src/hosts/inc)` is miss. Check it pls.

**Comment by alpencolt** [comment]
@leo60228 looks `NGEN_E_SYS_ASM_NI_MISSING` error code was deleted from .NET. Now we're making automatic generator of errors list depending of runtime you use.
This and some patches for .NET 5 will be released soon, hope this week

**Comment by viewizard** [comment]
@leo60228 I updated repo, this issue should be fixed by commit https://github.com/Samsung/netcoredbg/commit/7002d141de3eaa6c9d52941fb77eb2d1684dbc64
Could you please check build with CoreCLR 5.0 sources on you PC?

**Comment by viewizard** [comment]
Note, in CoreCLR 5.0 release, `cor.h` file is broken (g_tkCorEncodeToken relate issue), was fixed in upstream by https://github.com/dotnet/runtime/commit/353919f9711e9d6b9bc772d1f9d20cee155fdf14 commit.
You should patch your CoreCLR 5.0 sources (https://github.com/dotnet/runtime/tree/release/5.0) with https://github.com/dotnet/runtime/commit/353919f9711e9d6b9bc772d1f9d20cee155fdf14.patch in order to build netcoredbg.
